namespace PerfectApiTemplate.Application.Abstractions.Logging;

public sealed record RequestLogEntry(
    DateTime StartedAtUtc,
    DateTime FinishedAtUtc,
    long DurationMs,
    string Method,
    string Scheme,
    string Host,
    string Path,
    string? QueryString,
    int StatusCode,
    string? RequestContentType,
    long? RequestContentLength,
    string? ResponseContentType,
    long? ResponseContentLength,
    string? RequestHeaders,
    string? ResponseHeaders,
    string? RequestBody,
    string? ResponseBody,
    bool RequestBodyTruncated,
    bool ResponseBodyTruncated,
    long? RequestBodyOriginalLength,
    long? ResponseBodyOriginalLength,
    string? ClientIp,
    string? UserAgent,
    Guid? UserId,
    string? TenantId,
    string? CorrelationId,
    string? RequestId,
    string? TraceId,
    string? SpanId);

public sealed record ErrorLogEntry(
    DateTime CreatedAtUtc,
    string ExceptionType,
    string Message,
    string? StackTrace,
    string? InnerExceptions,
    string Method,
    string Path,
    string? QueryString,
    string? RequestHeaders,
    string? RequestBody,
    bool RequestBodyTruncated,
    long? RequestBodyOriginalLength,
    int? StatusCode,
    Guid? UserId,
    string? TenantId,
    string? CorrelationId,
    string? RequestId,
    string? TraceId,
    string? SpanId,
    string? EnvironmentName,
    string? MachineName,
    string? AssemblyVersion);

public sealed record TransactionLogEntry(
    DateTime CreatedAtUtc,
    string EntityName,
    string? EntityId,
    string Operation,
    string? BeforeJson,
    string? AfterJson,
    string? ChangedProperties,
    long DurationMs,
    string OperationId,
    Guid? UserId,
    string? TenantId,
    string? CorrelationId,
    string? RequestId,
    string? TraceId,
    string? SpanId);

